### PR TITLE
HW06 Imran Turganov

### PR DESCRIPTION
**Pull request by IMRUNya**

### CODE REVIEW

**Comment by kajigor** [comment]
You have the same unique mistakes as https://github.com/kajigor/fp-2024-cub-fall/pull/133/. I remind you that cheating is against the university code of conduct. If I see this again, you will fail the course.

**Comment by IMRUNya** [comment]
> You have the same unique mistakes as #133. I remind you that cheating is against the university code of conduct. If I see this again, you will fail the course.

I am sorry to hear that, but I was not using other students code. One of the things that I did for that homework is asking help from chatGPT, that was it.

**Comment by kajigor** [comment]
Do you think that mindlessly copying code from chatGPT is any better?

**Comment by IMRUNya** [comment]
> You have the same unique mistakes as #133. I remind you that cheating is against the university code of conduct. If I see this again, you will fail the course.



> Do you think that mindlessly copying code from chatGPT is any better?

No, I was just thinking it would be better to tell the truth. I am sorry if it sounded ignorant or offensive.

**Pull request closed without merging**
