### PR TITLE
YassineFounounou HW#1

### PR DESCRIPTION
**Pull request by YassineFnn**

### CODE REVIEW

**Comment by alex28sh** [comment]
@YassineFnn please pull github actions into your repo

**Comment by YassineFnn** [comment]
> @YassineFnn please pull github actions into your repo

Is it fine now ?

**Comment by YassineFnn** [comment]
> > @YassineFnn please pull github actions into your repo
> 
> Is it fine now ? Also, the test cases fail here on the repo but on my computer it passes all of the tests, what's the problem ?

**Comment by kajigor** [comment]
> > > @YassineFnn please pull github actions into your repo
> > 
> > 
> > Is it fine now ? Also, the test cases fail here on the repo but on my computer it passes all of the tests, what's the problem ?

Where do you see them failing? I see the green checkmark in your repo.

**Comment by YassineFnn** [comment]
> > > > @YassineFnn please pull github actions into your repo
> > > 
> > > 
> > > Is it fine now ? Also, the test cases fail here on the repo but on my computer it passes all of the tests, what's the problem ?
> 
> Where do you see them failing? I see the green checkmark in your repo.

I am sorry, I checked something else instead. So, my PR is fine now, right ?

**Comment by alex28sh** [comment]
ok 6/6

**Pull request closed without merging**
